# Generated by Django 5.1.2 on 2025-01-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('hotel_owner', 'Hotel Owner'), ('activity_lister', 'Activity Lister'), ('event_lister', 'Event_Lister')], default='user', max_length=20),
        ),
    ]
