# Generated by Django 5.1.4 on 2025-01-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='booking_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
