# Generated by Django 5.0.3 on 2025-01-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_purchase_booking_details'),
        ('package', '0013_package_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='package.activity'),
        ),
    ]
