# Generated by Django 5.1.2 on 2025-01-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_stripe_checkout_session_id_delete_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
