# Generated by Django 5.1.2 on 2025-01-24 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_booking_number_of_people'),
        ('package', '0013_package_hotels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('user', 'package', 'booking_date'), name='unique_booking'),
        ),
    ]
