# Generated by Django 5.1.2 on 2025-01-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_alter_booking_activity_alter_booking_hotel'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking',
        ),
    ]
