# Generated by Django 5.0.3 on 2025-02-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('No Refund', 'No Refund'), ('Refund Pending', 'Refund Pending'), ('Refunded', 'Refunded')], default='No Refund', max_length=20),
        ),
    ]
