# Generated by Django 5.0.3 on 2025-02-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_booking_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancellation requested', 'Cancellation requested'), ('refunded', 'Refunded')], default='Pending', max_length=50),
        ),
    ]
