# Generated by Django 5.0.3 on 2025-02-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
