# Generated by Django 5.1.2 on 2025-01-11 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_alter_package_duration_alter_package_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='package',
            name='base_price',
            field=models.FloatField(default=0.0, help_text='Minimum service charge'),
        ),
        migrations.CreateModel(
            name='UserCustomizedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0.0)),
                ('activities', models.ManyToManyField(blank=True, to='package.activity')),
                ('hotels', models.ManyToManyField(blank=True, to='package.hotel')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_customized_packages', to='package.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customized_packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
