# Generated by Django 5.1.2 on 2025-01-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_activity_price_hotel_price_package_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
