# Generated by Django 5.1.2 on 2025-01-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_alter_package_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
