# Generated by Django 5.1.2 on 2025-01-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0008_alter_package_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustomizedpackage',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='usercustomizedpackage',
            name='hotels',
        ),
        migrations.AddField(
            model_name='usercustomizedpackage',
            name='activities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='usercustomizedpackage',
            name='hotels',
            field=models.JSONField(default=list),
        ),
    ]
