# Generated by Django 5.1.2 on 2025-01-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0009_remove_usercustomizedpackage_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
