# Generated by Django 5.1.4 on 2025-01-14 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0010_alter_package_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days', models.IntegerField(default=1, help_text='Number of days for this hotel')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.hotel')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_hotels', to='package.package')),
            ],
        ),
    ]
