# Generated by Django 5.1.4 on 2025-01-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_packagehotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='hotels',
        ),
    ]
